volumes:
  es_data:
    name: steamrec_es_data

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    healthcheck:
      test: curl -s http://localhost:9200 >/dev/null || exit 1
      interval: 10s
      retries: 30

  backend:
    build: .
    container_name: steamrec-backend
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - ES_URL=http://elasticsearch:9200
    ports:
      - "8000:8000"
